# Project
version=1.0.1
group=com.sattik03.cooksense
java_version=21

# Common
minecraft_version=1.21.11
mod_name=CookSense
mod_author=Sattik03
mod_id=cooksense
license=MIT
credits=
description=Clean, client-side floating countdown timers and progress indicators above campfires.
minecraft_version_range=[1.21.9, 1.21.11]

neo_form_version=1.21.11-20251209.172050
parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Fabric
fabric_version=0.141.6+1.21.11
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.11.45
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
